data:extend({
  {
    type = "fluid",
    name = "molten-iron",
    default_temperature = 1500,
    max_temperature = 3000,
    heat_capacity = "0.425KJ",
    base_color = color.moltenmetal.base,
    flow_color = color.moltenmetal.flow,
    icon = "__Molten_Metals__/graphics/icons/molten-iron.png",
    icon_size = 64, icon_mipmaps = 4,
    -- pressure_to_speed_ratio = 0.4,
    -- flow_to_energy_ratio = 0.59,
    order = "a[molten-iron]",
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-copper",
    default_temperature = 1100,
    max_temperature = 2600,
    heat_capacity = "0.259KJ",
    base_color = color.moltenmetal.base,
    flow_color = color.moltenmetal.flow,
    icon = "__Molten_Metals__/graphics/icons/molten-copper.png",
    icon_size = 64, icon_mipmaps = 4,
    -- pressure_to_speed_ratio = 0.4,
    -- flow_to_energy_ratio = 0.59,
    order = "b[molten-copper]",
    auto_barrel = false
  },
  -- {
  --   type = "fluid",
  --   name = "acidic-water",
  --   default_temperature = 80,
  --   max_temperature = 100,
  --   heat_capacity = "0.1KJ",
  --   base_color = color.acidwater.base,
  --   flow_color = color.acidwater.flow,
  --   icon = "__Molten_Metals__/graphics/icons/acidic-water.png",
  --   icon_size = 64, icon_mipmaps = 4,
  --   -- pressure_to_speed_ratio = 0.4,
  --   -- flow_to_energy_ratio = 0.59,
  --   order = "z"
  -- },
})
